# -*- coding: utf-8 -*-
"""E6i part3 的静态登记内容 (不含任何后段数值): Q16 方法复盘的事实条目、全轮 coverage 的逐条映射。
coverage 状态取值: done / reused / changed / deferred / unavailable (brief §15)。
状态里需要现场核对的项 (C1 / C2 完成与否、git 提交) 由 part3 生成器按产物存在性覆盖。"""

Q16_ITEMS = [
    dict(item='规划侧事实错误 #43（把 I11 的 P25–P55 截面分位写成 +25–55% 涨幅，推"强漂移"先验）',
         where='proposal → plan W01 → brief §0.1', caught_by='web plan W01（执行前）', effect='proposal 的"强漂移 → RS/YZ 适配"先验删除；估计量全保留，适配交 Stage 1 实测',
         root_cause='fact_error（凭摘要 / 记忆写事实句；复盘根因 C）', next_change='引用信号 / 阈值先重读定义函数并带单位（纪律 ⑧ 补句）'),
    dict(item='动机链第一步："被错剔赢家"画像是 E6h→E6i 的出发点',
         where='R0 §T0（Q18）', caught_by='R0 同人数 pool0 对照', effect='画像三要素方向保持，但与 pool0 同人数随机对照同号 172/172、202/202（量级比 0.98 / 0.91）→ 是池子层面的收益预测，不是"错剔"特有',
         root_cause='measurement / 未匹配比较（复盘根因 B）', next_change='画像 → 假设前先过 pool0 同人数对照（纪律 ㉓ 已有，本轮首次用上）'),
    dict(item='A0 编译遗漏三次（v1.1 四臂参数、v1.2 RR cr5 焦点"两者"臂、v1.3 RA 最高 K 换出 + 四臂 K x A 的 M2）',
         where='A0 编译器 vs plan §5.3 / §5.4.2 / §5.7 / brief §6', caught_by='执行端对照 plan 原文', effect='均为"只新增不改旧行"的补登记，信息暴露逐次登记（exposure_ledger）',
         root_cause='execution（编译器没有逐条对照 plan 参数清单）', next_change='A0 编译后加一步"plan 参数清单 → 描述符计数"的自动对账，缺项即不开跑'),
    dict(item='B 草稿写"Z-MAP 后段不复跑"', where='E6i_record_B_draft.md §3 / §2', caught_by='执行端开 Stage 3 前重读 brief §8',
         effect='批准文件登记更正；后段照 brief §8 跑 Z-MAP；冻结对象不变', root_cause='fact_error（草稿生成器文字凭记忆写，没回读 brief §8；与根因 C 同类）',
         next_change='B 草稿的"后段读法"段逐字取自 brief §8，不由生成器自由撰写'),
    dict(item='报告口径错误在交付前被抓（路径数按 H 重复计约 4 倍；两个登记方向合并取中位把一个方向的读数盖住；M1 角色映射空；四臂 M2 的 α 标签取错列）',
         where='part1a / part1b 生成器', caught_by='执行端自审 + 审阅者', effect='全部在交付前修正；账户与统计未受影响',
         root_cause='execution / 口径（复盘根因 F：汇总单位与分组未写进表头即被默认）', next_change='汇总单位（配置 vs 描述符）与分组键写进表头；"按登记方向分开读"作为生成器默认'),
    dict(item='竞争解释里写了一个在排序引擎中恒等于母体的对照（"原 K 以同 α 再混入一次"），并把 log K ≈ 0 当作对"同向加权"解释的反驳',
         where='part1a Q2 初稿', caught_by='审阅者', effect='删去该对照；log / floor ≈ 0 改为"引擎一致性检查，不作证据"',
         root_cause='measurement / 读法（对照设计没先问"这个对照在引擎里是否恒等"）', next_change='新提对照先写出它在引擎里的零点与可区分的备择'),
    dict(item='相对生产 H5 的脚本逐描述符重读整块 npz，内存约 684 GB', where='e6i_vs_h5.py 首版', caught_by='执行端监控 RSS',
         effect='按 PID + 启动时间停掉、改为每文件读一次后重跑；产物未受影响', root_cause='execution', next_change='读 npz 一律"每文件一次 + 行 copy"（其余脚本已核）'),
    dict(item='推导段正 ≠ 后段可分辨（功效）', where='part2 §3 / §8', caught_by='设计内（MDE 事前登记）',
         effect='后段合计约 7.2 年，MDE 比推导段大；区间跨零首先是功效问题', root_cause='precision',
         next_change='下一轮对"推导段为正、后段不可分辨"的对象，事前写出需要多少年才能分辨（纪律候选 ㉖ 功效量化）'),
]

COVERAGE = [
    # (来源, 条目, 状态, 理由 / 说明, 影响)
    ('brief §0.1', '规划说明与 proposal 勘误（#43）', 'done', 'preregistration.md 逐字；source_corrections_E6i.md 12 条', '无'),
    ('brief §0.2', '六类硬约束', 'done', 'E7 未读；守卫（推导段 + 记录 B 后）测试 guard_attack_tests*.json；地基与 e6e–e6h 未改；并发 ≤ 24；git 白名单；无登录信息', '无'),
    ('brief §1 / plan §11.4', 'P0 起点：源码核验、指纹、数据契约、母体展开', 'done', 'source_resolution.md、checks/p0_source_facts_*、engine / rule / feature / label 锚', '无'),
    ('brief §2 / plan §4–§5', 'A0 登记（目录 276 成员、需求 × 估计量 × 角色映射、manifest）', 'changed', 'v1.0 → v1.3 三次只新增的补登记（编译遗漏）；信息暴露逐次登记', '新增对象与旧对象分开列出'),
    ('brief §3 / plan §11.3', 'Stage 0 仪器：ADEMP 仿真、恒等锚、前视自动审计', 'done', 'checks/simulation_ADEMP.md、simulation_results.csv、suffix_guard、plan_contract_tests', '无'),
    ('brief §4 / plan Stage 1', 'Stage 1 测量诊断（Q3 首表、Q11 C3、Q12、Q17 / Q18 的 Stage 1 部分）→ REPORT_R0', 'done', 'exec_briefs/E6i_REPORT_R0.md', '无'),
    ('brief §5 / plan §11.1', 'A1 规划复核', 'deferred', '规划 session 未做；用户在记录 B 时指示继续', '本轮无 A1 增补；事后 A1 只能作下一轮登记'),
    ('brief §6 / plan §5', 'Stage 2 角色账户（SLOT / ADD / VETO / SOFT / SWAP / FOCAL / RL；四母体；H 网格含快端）', 'done', '两段各 35,384 主描述符 SUCCEEDED、0 FAILED_TECH', '无'),
    ('plan §5.4', 'SWAP 换入 / 换出全分布', 'done', 'part1a §5b（推导段）', '无'),
    ('plan §5.5', '相对生产 H5 的完整增量（与同 H 分列）', 'done', 'part1a §5c；part2 §9 另加 R1@H5 / R2@H5', '无'),
    ('plan §5.6 / §5.7', '四臂中心与交互', 'done', 'part1a Q15；part2 Q15', '无'),
    ('plan §6.3 / §6.4', 'Z-MAP 随机对照（三类机制；MCSE 加轮）', 'done', '推导段与后段两段 MCSE ≤ 0.05 年化百分点', '无'),
    ('plan §6.5', '归因（进入 / 退出 / 共同成员）', 'done', '逐日恒等残差 ≤ 1e−17 量级', '无'),
    ('plan §7.1', 'M0 固定代表', 'done', 'part1a §5 + 附录 A；part2 代表节', '无'),
    ('plan §7.2', 'M1 共识 + 等资本合并', 'done', '两段各 1,512 程序（推导）；后段同清单', '无'),
    ('plan §7.3', 'M2 形状校准分支（part1b）+ 256 次时间块重采样', 'changed', 'M2 作 part1b 子交付；后段按冻结规则逐年用全部已成熟历史重训（Stage 3 技术改动：多段训练）', '学习不确定性只在推导段、条件于已拟合程序路径'),
    ('plan §8', '统计：NW 三种 lag、2,000 次 bootstrap（块 20 / 60）、三层同时带、Z-MEAN、δ 与 MDE、状态词、逐年、LOYO', 'done', '推导段 statistics/；后段 statistics/post/（含四段合并、去 2015+16、去 2024+）', '无'),
    ('brief §7', '记录 B（需求域包；用户授权）', 'done', '整表 43 包 + 技术包；用户原话与解读见 approval_provenance.json；草稿"Z-MAP 后段不复跑"已更正', '无'),
    ('brief §8', 'Stage 3 后段首次观察（两段一次算完、封存回执、P20 / P21 按原主读数）→ REPORT_part2', 'done', 'registry/first_look_receipts.json；exec_briefs/E6i_REPORT_part2.md', '不是 OOS'),
    ('brief §9', 'Stage 4：结果卡、factor_iteration_delta、research_catalog_v36、候选库更新提案、线状态 / park 草稿 → REPORT_part3', 'done', 'reports/ 下各文件', '定案权在规划 session 与用户'),
    ('brief §10 / plan §9.1', 'C1：N x 行业宽度交叉（64 seed、两种分配、两种评分 scope、桥与仪器效应）', 'done', 'carried/C1/、sealed/（后段）→ carried/summary/', '偏相关不证明历史成因'),
    ('brief §10 / plan §9.2', 'C2：冲击成本透镜（A x κ 平方根、线性另表、Q/ADV20 压力代理、容量根）', 'done', 'carried/C2/ → carried/summary/', 'κ 未校准，不输出可部署规模'),
    ('brief §10 / plan §9.3', 'C3：signal_margin_profile', 'done', 'R0 §9（只描述，不重建信号）', '无'),
    ('brief §11', '统计与账本口径', 'done', '同 plan §8', '无'),
    ('brief §12', '事前登记逐字落盘', 'done', 'preregistration.md（sha d5312ce8…）未改', '无'),
    ('brief §13', '自测与验收（锚、反例、状态和 = 登记数、receipt）', 'done', 'checks/；task_status/', '无'),
    ('brief §14', '运行组织（计时、并发 ≤ 24、BLAS ≤ 4）', 'done', 'WORKLOG；chain 日志', '无'),
    ('brief §15', '交回：结果目录、REVIEW_input、engine_contract、四份 REPORT、WORKLOG、git 白名单 + push', 'done', 'exec_briefs/；reports/E6i_REVIEW_input.md', '无'),
    ('plan §4.9', '考虑过但未构造（Pástor–Stambaugh、Kyle λ、tick 跳跃、概念图、DFA、turnover_ff、L2）', 'unavailable', '数据不可得或无当前母体需求（consideration_ledger C）', '未构造 ≠ 无效'),
    ('proposal', 'headline：因子端迭代 · 估计量族 x 策略适配（八族同等深度）', 'done', '八轴 276 成员；Stage 1 → Stage 2 → 后段', '无'),
    ('proposal', '记录 B ≤ 12 描述符、v36 一族一支', 'changed', 'plan W17：按需求域包；研究目录与候选库更新提案分开、由用户定', '无'),
    ('proposal', '40 键按需准入', 'changed', 'consideration_ledger B 部分（86 个 E6h 登记键的本轮覆盖方式）', '部分键本轮未覆盖'),
    ('proposal', '信号线 carried 零算力 + D-S 面板', 'done', 'C3 signal_margin_profile', '无'),
]
