# -*- coding: utf-8 -*-
"""E6i 结果卡 (plan §10.2) 的判断性字段 —— 执行端的读法, 规划 session 复核。数字一律由 e6i_hypothesis_outcomes.py 现算后填入
{占位键}; 这里只写判断与理由。prediction_status ∈ {aligned, opposed, mixed, underidentified, untested};
root_cause_evidence ⊂ {fact_error, measurement, role, capital, time, precision, execution, unknown}。
本文件分两批写: 第一批 (Q11 / Q12 / Q16 / Q17 / Q18) 只依赖 Stage 1 与推导段; 第二批在后段首次观察封存回执之后写。"""

J = {
    'Q1': dict(
        prediction_status='mixed',
        root_cause_evidence=['time', 'precision', 'role'],
        root_note='推导段"少量加、不能换"成立（α ≤ .25 小正、完全替换大负）；后段小权重加接近 0、完全替换仍大负，20 日 level x CV 复合（TPAIR）由推导段为正转为后段为负。'
                  '成员层推导合并与后段合并中位都为正的 T 成员是三个 20 日绝对尺度（T_std20 / T_mad20 / T_iqr20，part3〔P3-BOTH〕，各自读数最高的角色为 COMMON_SUPPORT），'
                  '但在固定中间档配置下 2024-26 为负或接近 0（候选库提案）。',
        what_was_not_tested='同窗口内"水平"与"离散"的分离（例如水平匹配后的 CV）没有登记；T 的事件剥离版本只在两个窗口。',
        what_cannot_be_concluded='不能由 CV 与原 T 相关较低宣布 CV 更好；不能把"小权重加在推导段为正"读成后段也会为正。',
        next_design_change='若继续 T：先登记"水平匹配后的离散"以分离水平与离散；20 日绝对尺度成员在固定配置下 2024-26 不稳，本轮不进 E7 短名单，'
                           '若要作 E7 的次级观察对象，须事前固定配置（COMMON_SUPPORT、小 α）。',
        why='后段两期为正的 T 成员只剩 20 日绝对尺度，且在固定配置下 2024-26 不稳；复合与比值版本在后段反转。',
        new_information_needed='E7 账户；水平匹配后的离散测量。'),
    'Q2': dict(
        prediction_status='mixed',
        root_cause_evidence=['time', 'precision', 'unknown'],
        root_note='推导段强正（三母体两段、三种机制对照同向）；后段 2019-23 仍为正但约为推导段的三分之一，2024-26 为负（2024 年最差），后段合并接近 0；'
                  '对匹配随机两后段都为正——排序信息没有消失；对母体自己的核心 K，2019-23 小正（+0.086）、2024-26 为负（-0.233）。成员层：K_samt20 / K_amt20 / K_slope20 与源桥 K_MA3 两期都为正。',
        what_was_not_tested='新信息与"同向加权"的分离（按新旧排序分歧分层）；含冲击成本的视图见 part3（C2）。',
        what_cannot_be_concluded='不能说 K 响应族能改进生产母体；也不能说它无信息（对随机两后段为正）。成员层两期为正的名单是从 276 个成员里按结果筛出，存在赢家诅咒。',
        next_design_change='① 把响应族少数成员（按族事前固定，不按后段挑格）在小 α、长 H 下登记为 E7 首次观察；② 登记"新旧排序分歧分层"设计以分离新信息与同向加权。',
        why='后段首次观察把"推导段强正"缩到"2019-23 小正、2024-26 反向"；只有 OOS（E7）能区分效应变小与推导段乐观。',
        new_information_needed='E7 账户；分歧分层账户。'),
    'Q3': dict(
        prediction_status='opposed',
        root_cause_evidence=['capital', 'time'],
        root_note='保留集删除 / 缩减在两期都让母体变差，同资本口径接近 0（资本效应）；2024-26 反向删除（删掉低风险名字）明显为正——V 的方向在该段反转。',
        what_was_not_tested='以市场状态为条件的 V 用途（例如只在低波动状态删除高风险名字）没有事前登记。',
        what_cannot_be_concluded='不能把删除的负结果读成"风险分离无效"；分层 IC 在 Stage 1 保留。',
        next_design_change='V 不再作无条件删除；若继续，事前登记一个市场状态条件（例如用已公开的波动状态划分）再测。',
        why='两期的负结果主要是资本效应，且方向随状态反转；无条件删除在两种状态下都不合适。',
        new_information_needed='状态条件下的账户。'),
    'Q4': dict(
        prediction_status='opposed',
        root_cause_evidence=['capital', 'role'],
        root_note='O 的保留集删除两期都为负，同资本口径接近 0；把原焦点否决改成只在跳空状态执行，真实状态不优于随机状态（推导段），后段接近 0。',
        what_was_not_tested='O 的正向用途（加分 / 换入）只在 P22 的反向读法里讨论过，本轮没有登记。',
        what_cannot_be_concluded='不能由"坏否决"推出"高跳空必买"。',
        next_design_change='O 的删除角色在这几个母体上降为低优先级；如重开，只作事前阈值的状态条件。',
        why='两期一致为负、机制读数不支持。',
        new_information_needed='—'),
    'Q5': dict(
        prediction_status='opposed',
        root_cause_evidence=['role', 'measurement'],
        root_note='同人数 SWAP 两期都对母体为负；按 P21 的原主读数（匹配随机），SWAP 在后段两段都为负——E6h 的"画像级保留"在这个算子上后段不成立；反转域小权重 ADD 推导段小正、后段接近 0 或为负。',
        what_was_not_tested='把同业相对位置作为 K / T 槽位里的排序分量（而不是换入算子）没有登记。',
        what_cannot_be_concluded='不能由 SWAP 的负结果推出"同业相对位置没有信息"；只对该算子 x 母体 x 时期成立。',
        next_design_change='同业相对位置从"换入算子"转为"槽位内分量"登记（与 Q18 的读法一致）。',
        why='换入算子在两期、两种读数下都为负，问题更可能在角色。',
        new_information_needed='槽位分量版本的账户。'),
    'Q6': dict(
        prediction_status='mixed',
        root_cause_evidence=['time'],
        root_note='推导段 C 替代形式都为负、原 CVR_20d 否决有价值；后段 A06 的 C 核心槽位转为两段非负，40 日 C 成员只在后段为正；关掉 CVR 否决在后段仍更差。',
        what_was_not_tested='C 核心槽位在 R1 / R2 上（按 plan 规则只在 A06）。',
        what_cannot_be_concluded='不能由后段转正推出 C 替代优于 CVR_20d；只后段为正的成员不能当作候选。',
        next_design_change='保留 CVR_20d 否决；C 核心槽位列为低优先级研究，E7 如有余量再看。',
        why='C 的后段转正只出现在一个母体与一个时期，证据弱。',
        new_information_needed='—'),
    'Q8': dict(
        prediction_status='mixed',
        root_cause_evidence=['precision', 'time'],
        root_note='M1 共识的符号跟随路线与方向（推导段 K 响应族共识为正，后段转负）；M2 两期对母体都接近 0；内层选择零修改的 (程序 x 年) 占比四段 13% / 53% / 46% / 77%。',
        what_was_not_tested='M2 以外的家族学习程序（例如多成员联合 basis）。',
        what_cannot_be_concluded='"族内没有冠军"不否定族整体；M2 ≈ 0 不说明形状不存在。',
        next_design_change='M2 降为低优先级；M1 不再单独作路线，只作单成员结果的稳健性列。',
        why='两期都没有提供超过单成员账户的信息。',
        new_information_needed='—'),
    'Q9': dict(
        prediction_status='mixed',
        root_cause_evidence=['time', 'precision'],
        root_note='后段整体对母体为负且正值几乎消失（NW 排除 0 为正的描述符从推导段约 2 千降到约 2 百）；路线之间的相对好坏保持（秩相关约 0.65）；推导段的主要正结果 K 槽位（推导 NW 区间排除 0：正 736 / 负 0）缩到接近 0。',
        what_was_not_tested='E7（2026-03-27 之后）是唯一 OOS，本轮不开。',
        what_cannot_be_concluded='后段不是 OOS；区间跨零与两段不同号都不是淘汰标签。',
        next_design_change='下一轮 E7 前的登记只从"两期都为正、机制读数一致"的少数对象里事前固定，并写出功效（需要多少年才能分辨）。',
        why='后段首次观察已经把候选范围大幅收窄；再在同一历史上挑格只会增加选择偏差。',
        new_information_needed='E7。'),
    'Q13': dict(
        prediction_status='opposed',
        root_cause_evidence=['measurement', 'role'],
        root_note='A 成员同预算换入（两种换出规则）两期都为负、对匹配随机也不占优；K_rar 登记主方向两期为负、竞争方向推导段与 2019-23 为正——方向继承规则对这个派生量不成立。',
        what_was_not_tested='K_rar 按竞争方向重新登记后的首次观察（本轮不改方向）。',
        what_cannot_be_concluded='不能由 A 换入为负推出"事件基线无信息"；只对该角色 x 母体成立。',
        next_design_change='K_rar 的方向交规划 session：若改登记方向，作为新对象事前登记，不追认。',
        why='两期都支持竞争方向；但改方向必须是新的事前登记。',
        new_information_needed='按新方向登记后的 E7 账户。'),
    'Q14': dict(
        prediction_status='opposed',
        root_cause_evidence=['time', 'role'],
        root_note='推导段状态内按 R_peer20 换入"真实 > 匹配随机 > 反向"；后段对母体大负、对匹配随机也为负——机制读数在后段不成立。',
        what_was_not_tested='S 作为槽位权重的条件（而不是换入条件）。',
        what_cannot_be_concluded='不能把同行状态当作全局 regime；不把行业均值当板块共振发现。',
        next_design_change='S 的条件换入降为低优先级。',
        why='后段两种读数都为负。',
        new_information_needed='—'),
    'Q15': dict(
        prediction_status='mixed',
        root_cause_evidence=['capital'],
        root_note='推导段 T level x CV 的交互为正（CV 单独替换为负、与水平合用不再为负），K 残差 x A 事件交互为负；后段四组交互都为正，但都来自单臂亏损合用后不叠加（合用亏得少于两臂之和），不是合用带来正收益。',
        what_was_not_tested='四臂之外的组合。',
        what_cannot_be_concluded='交互只对登记对象成立，不推广为"同族因子互补"。',
        next_design_change='四臂不作为下一轮主线；T level x CV 的"合用避免 CV 单独替换的损失"作为 T 构造的约束（不单独用 CV 替换 T）。',
        why='交互为正但合用本身两期多为负。',
        new_information_needed='—'),
    'Q7': dict(
        prediction_status='aligned',
        root_cause_evidence=['capital'],
        root_note='按价差代理替换边缘名单在 8bp 线性成本下两期都为负（主要损失 gross）；在平方根冲击的重情景下转为正——它省下的是冲击成本（减少交易、偏向低冲击票），'
                  '不是信息 alpha。删除类路线在重冲击下转正是同一效应。这与 Q7 的预期一致："交易代理可能主要改变成本，不改变 gross"。',
        what_was_not_tested='κ 的校准（需要成交数据）；分钟级执行曲线；AR / CS / EDGE 三个价差对象各自作边缘替换的分开账户（本轮按族汇总）。',
        what_cannot_be_concluded='不能称信息 alpha 或真实容量；κ 未校准，不输出可部署规模；冲击下的"转正"多来自短 H 与大资金这类母体本身已严重为负的区域。',
        next_design_change='若关心实施：在长 H、母体仍为正的规模区间内，把摩擦测量作为执行层约束（而不是选股分量）单独登记，并先做 κ 校准。',
        why='重冲击下的改善集中在不可部署区域；只有校准后的冲击模型能判断它在实际规模下是否存在。',
        new_information_needed='成交数据与 κ 校准。'),
    'Q10': dict(
        prediction_status='mixed',
        root_cause_evidence=['precision'],
        root_note='推导段 pool0 较小，N ≥ 150 或 B = 8 的格多数日子行业容量不足，严格交叉在 2010-14 没有充分支持、2015-18 只有 N = 100 的宽度对比可读（约 0）；'
                  '2019–2026 有充分支持：固定行业宽度时人数 100 → 250 的差在两个后段所有格都为正，固定人数时行业 8 → 16 的差小且两个后段方向不同。'
                  '桥：截断可选池会降低收益，按核心分数截断比随机截断损失小。',
        what_was_not_tested='推导段的 N / B 分离（数据支持不足，不能靠放宽可行性补）；其他母体。',
        what_cannot_be_concluded='只识别"在此抽样与评分机制下改变 N / B 的账户差异"，不识别历史真实扩容的原因；偏相关不作唯一机制。',
        next_design_change='若继续这条线：以 2019–2026 的结果为先验，把"可选池人数"作为母体构造参数事前登记（例如 pool0 截断下限），E7 检验；推导段不再尝试强行分离。',
        why='人数效应在有支持的两个后段方向一致、幅度大；宽度效应不稳定。',
        new_information_needed='E7 下的同一 N / B 对比。'),
    'Q11': dict(
        prediction_status='aligned',
        root_cause_evidence=['fact_error'],
        root_note='原 proposal 把 I11 的 P25–P55 截面分位写成 +25–55% 涨幅（规划侧 #43，web plan W01 抓出）；Stage 1 实测纠正了这一前提。',
        what_was_not_tested='阈值变化的敏感面（需要重建 signal / observation / pool，属于另一研究对象与授权）；后段的 C3 描述（C3 只在推导段做）。',
        what_cannot_be_concluded='不能由 C3 描述推出"信号应该改"或任何新信号的绩效。',
        next_design_change='信号线若推进，另立对象：在固定 I11 之外登记阈值 / 事件时钟的替代版本，按同一记录 B 流程做首次观察。',
        why='C3 只能描述现有边界附近的收益；要区分"阈值位置"与"事件时钟"两种解释，必须真正改变构造。',
        new_information_needed='不同阈值 / 日龄截断下的完整账户（需要新授权）。'),
    'Q12': dict(
        prediction_status='aligned',
        root_cause_evidence=[],
        root_note='H==L 在本数据几乎全是触板日（P0：未触板的 H==L ≈ 5e−6），源 NaN 处理与 OBS 在排序上几乎等价；差异集中在 LIMIT_SENS。',
        what_was_not_tested='限价政策对 V 以外轴（O 的跳空、K 的响应）的系统影响只在 V 的 obs / ls 成员上成对登记。',
        what_cannot_be_concluded='不能把"账户上无系统差"读成"触板日没有信息"；也不能把机械影响一概视为无用。',
        next_design_change='若某轴的测量在触板日有明确经济含义（例如跳空 / 封板），把 OBS / LIMIT_SENS 成对登记扩到该轴。',
        why='目前只有 V 的成对版本，其他轴的限价敏感性没有被测。',
        new_information_needed='O / K 轴的成对限价版本。'),
    'Q16': dict(
        prediction_status='mixed',
        root_cause_evidence=['fact_error', 'measurement', 'execution', 'precision'],
        root_note='本轮方法层问题见 part3 §5 逐条（事实错误 #43、动机链第一步被 R0 对照削弱、A0 三次编译遗漏、B 草稿写法与 brief 不符、报告口径错误在交付前被抓、一个在引擎里恒等的对照、内存事件、功效）。',
        what_was_not_tested='—',
        what_cannot_be_concluded='不能把各轴的负结果只写成"样本噪声"或"这个方向已经没有可做的"；也不保证下一轮一定能找到新解释。',
        next_design_change='① A0 编译后自动对账"plan 参数清单 → 描述符计数"；② 事实句（阈值 / 单位 / 符号）一律回读定义函数；③ 生成器默认按登记方向分开读、表头写汇总单位；④ 新对照先写出它在引擎里的零点。',
        why='这些都是本轮实际发生、且会在下一轮重复的错误来源；前三项已有具体触发实例。',
        new_information_needed='—'),
    'Q17': dict(
        prediction_status='underidentified',
        root_cause_evidence=['precision'],
        root_note='Stage 1 的分组条件形状在两段都被标出的 (成员, 集合, 母体) 只有少数；M2 的 u² 项在少数 (程序 x 年) 里占主导，u² 符号多年一致的比例中等；M2 账户对母体接近 0。',
        what_was_not_tested='非单调形状的专门角色（例如按形状分段的 SLOT）没有登记；M2 只用 [u, u², u·z] 一种低维 basis。',
        what_cannot_be_concluded='训练内形状不推出"非单调可用"；不能把 M2 对母体 ≈ 0 读成"形状不存在"。',
        next_design_change='若要检验非单调用途，事前固定形状（例如两端都差的 U 形）并登记成新角色，而不是让 M2 在训练内学。',
        why='M2 的内层选择零修改的 (程序 x 年) 占比 2015-18 为 53%、后段 46% / 77%，学到的形状不稳定；事前固定形状能把"形状"与"学习噪声"分开。',
        new_information_needed='事前固定形状角色的推导段与后段账户。'),
    'Q18': dict(
        prediction_status='mixed',
        root_cause_evidence=['measurement'],
        root_note='新测量（T 的 20 日离散、K 的残差响应、R 的同业相对）比旧 std60 / K0 / skip1 分离更强，V 的 RS / YZ 与旧 Parkinson 相当——这部分与预期一致；但"被错剔赢家 − 被剔输家"的画像与 pool0 同人数随机对照同号且量级相当，说明它是池子层面的收益预测，不是"错剔"特有——这部分与 E6h→E6i 的动机相反。',
        what_was_not_tested='按真实漂移与触板天数分层后的画像在后段的复核（画像只在推导段做）。',
        what_cannot_be_concluded='不能由画像推收益；不能把"画像保持"读成"否决错剔了这些票"。',
        next_design_change='以后把画像当作"池子层面的预测变量"来路由（进 K / T 槽位），而不是当作"修补否决"的依据。',
        why='R0 的同人数对照已经表明画像不特定于被拒绝集。',
        new_information_needed='—'),
}
